/**
 * Version information for familyzoo-v14
 * Auto-generated by sharpee - DO NOT EDIT
 */
export const STORY_VERSION = '0.0.2';
export const BUILD_DATE = '2026-09-17T07:02:48Z';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE } as const;
